/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║                    CODE-IDE • NeoMods                      ║
 * ║                  Advanced Android IDE Project              ║
 * ╚══════════════════════════════════════════════════════════════╝
 *
 *  (っ◔◡◔)っ ♥
 *
 *  Developer         • NeoMods
 *  Telegram Contact  • @NeoModsDev
 *  Telegram Channel  • https://t.me/NeoModsChannel
 *
 * ──────────────────────────────────────────────────────────────
 *  PROJECT NOTICE
 * ──────────────────────────────────────────────────────────────
 *
 *  This source file is part of the CODE-IDE project.
 *
 *  Unauthorized copying, extraction, redistribution,
 *  mirroring, downloading, modification, or reuse of
 *  CODE-IDE source files is NOT permitted without
 *  explicit permission from the developer.
 *
 *  The application may expose certain components in
 *  read-only mode for educational or preview purposes,
 *  however this DOES NOT grant permission to reuse
 *  or redistribute the source code.
 *
 *  If you need access to the original source code,
 *  implementation details, licensing, or collaboration,
 *  please contact the developer directly.
 *
 *  © NeoMods — All Rights Reserved
 * ──────────────────────────────────────────────────────────────
 */



package com.neo.ide.lsp.java.models

/**
 * Diagnostic codes are unique IDs for java diagnostic types.
 *
 * @author Akash Yadav
 */
enum class DiagnosticCode(val id: String) {

  // -------- Warnings generated by the IDE --------------
  /** Unused method parameter. */
  UNUSED_PARAM("ide.java.unused.param"),

  /** Unused local variable. */
  UNUSED_LOCAL("ide.java.unused.local"),

  /** Unused field. */
  UNUSED_FIELD("ide.java.unused.field"),

  /** Unused method. */
  UNUSED_METHOD("ide.java.unused.method"),

  /** Unused class. */
  UNUSED_CLASS("ide.java.unused.class"),

  /** Exception not thrown in method body. */
  UNUSED_THROWS("ide.java.unused.throws"),

  /** Unknown unused element. */
  UNUSED_OTHER("ide.java.unused.other"),

  /** A block with no statements i.e. an empty block */
  EMPTY_BLOCK("ide.java.empty.block"),

  // ------------ Compiler warnings and errors ------------
  UNCHECKED("compiler.warn.unchecked.call.mbr.of.raw.type"),
  DOES_NOT_OVERRIDE_ABSTRACT("compiler.err.does.not.override.abstract"),
  NOT_IMPORTED("compiler.err.cant.resolve.location"),
  NOT_THROWN("compiler.err.unreported.exception.need.to.catch.or.throw"),
  MISSING_CONSTRUCTOR("compiler.err.var.not.initialized.in.default.constructor"),
  MISSING_METHOD("compiler.err.cant.resolve.location.args");

  companion object {
    @JvmStatic
    fun forId(id: String): DiagnosticCode {
      return values().first { id == it.id }
    }
  }
}
