# SDK
compileSdk=36
minSdk=30
targetSdk=36
ndkVersion=27.0.12077973

# App
appVersionCode=1
appVersionName=1.0.0

# Gradle Plugins
agpVersion=8.2.0
kotlinVersion=1.9.21

# AndroidX
coreKtxVersion=1.12.0
appcompatVersion=1.6.1
materialVersion=1.11.0
constraintLayoutVersion=2.1.4
coordinatorLayoutVersion=1.2.0
drawerLayoutVersion=1.2.0
recyclerviewVersion=1.3.2
viewpager2Version=1.0.0
viewpagerVersion=1.0.0
fragmentKtxVersion=1.6.2
lifecycleVersion=2.7.0
annotationVersion=1.7.1
dynamicAnimationVersion=1.0.0-alpha03
activityKtxVersion=1.8.2
transitionVersion=1.4.1
preferenceVersion=1.2.1
windowVersion=1.1.0

# Third party
lottieVersion=6.3.0
okhttpVersion=4.12.0
jsr305Version=3.0.2
coroutinesVersion=1.7.3
guavaVersion=24.1-jre
markwonVersion=4.6.2
hiddenApiBypassVersion=6.1
commonsIoVersion=2.5
commonsCompressVersion=1.26.1
xzVersion=1.9
jsonVersion=20231013
desugarVersion=1.1.5

# Editor
soraEditorVersion=0.24.4

# Tree-sitter
treeSitterVersion=4.3.1

# LSP
lsp4jVersion=0.21.0
gsonVersion=2.10.1

# Event Bus
eventBusVersion=3.3.1

# Logging
slf4jVersion=1.7.36

# Code Generation
javaPoetVersion=1.13.0

# UI
flexboxVersion=3.0.0
autoServiceVersion=1.1.1
blankjVersion=1.31.1
javaParserVersion=3.26.1
androidToolsVersion=31.4.1
androidToolsAnnotationsVersion=31.2.2
aapt2ProtoVersion=8.3.0-10880808
