# SDK
compileSdk=36
minSdk=30
targetSdk=36

# App
appVersionCode=1
appVersionName=1.0.0

# AndroidX
coreKtxVersion=1.12.0
appcompatVersion=1.6.1
materialVersion=1.11.0
constraintLayoutVersion=2.1.4
coordinatorLayoutVersion=1.2.0
drawerLayoutVersion=1.2.0
recyclerviewVersion=1.3.2
viewpager2Version=1.0.0
fragmentKtxVersion=1.6.2
lifecycleVersion=2.7.0
annotationVersion=1.7.1
dynamicAnimationVersion=1.0.0-alpha03
activityKtxVersion=1.8.2
transitionVersion=1.4.1

# Third party
lottieVersion=6.3.0
okhttpVersion=4.12.0
jsr305Version=3.0.2
coroutinesVersion=1.7.3
